# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pull Request Triggers (triggers the pipeline whenever a pull request is opened with the specified target branches)
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool:
  vmImage: ubuntu-latest

stages:
- stage: Check_cppcheck
  jobs:
  - job: CheckStage
    steps:
    - script: |
        if ! command -v cppcheck &> /dev/null
        then
          echo "ko tim thay cppcheck..."
          echo "cai dat cppcheck..."
          sudo apt-get update
          sudo apt-get install -y cppcheck
        else
          echo "cppcheck da cai dat"
        fi
      displayName: 'Install cppcheck'

- stage: Run_cppcheck
  jobs:
  - job: RunStage
    steps:
    - script: |
        cppcheck --version
        cppcheck --enable=all ../src/track1/*.* ../src/track2/*.*
      displayName: 'Run cppcheck'
