# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pull Request Triggers (triggers the pipeline whenever a pull request is opened with the specified target branches)
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

#Installing GCC
- script: |
    if ! command -v gcc &> /dev/null
    then
      echo "GCC not found, installing..."
      sudo apt update
      sudo apt install -y gcc
    else
      echo "GCC already installed"
    fi
  displayName: 'Install GCC'

#Installing cppcheck
- script: |
    if ! command -v cppcheck &> /dev/null
    then
      echo "cppcheck not found, installing..."
      sudo apt-get update
      sudo apt-get install -y cppcheck
    else
      echo "cppcheck already installed"
    fi
  displayName: 'Install cppcheck'

#Run cppcheck
- script: |
    cppcheck --version
    cppcheck --enable=all ./src/track1/*.*
    cppcheck --enable=all ./src/track2/*.*
  displayName: 'Run cppcheck'

- script: |
    echo "Running gcc"
    cd src/track1
    gcc -o test test.c 2> error.log

    if [ -s error.log ]; then
        echo "Bugs found, check error.log for detail"
    else
        echo "There's no error"
    fi
      
  displayName: 'Run GCC'
